import{r as t,j as m}from"../../assets/jsx-runtime.js";import{M as b,u as L,P as k,a as S,b as $,L as A,m as D}from"../../assets/proxy.js";class K extends t.Component{getSnapshotBeforeUpdate(f){const e=this.props.childRef.current;if(e&&f.isPresent&&!this.props.isPresent){const n=this.props.sizeRef.current;n.height=e.offsetHeight||0,n.width=e.offsetWidth||0,n.top=e.offsetTop,n.left=e.offsetLeft}return null}componentDidUpdate(){}render(){return this.props.children}}function N({children:u,isPresent:f}){const e=t.useId(),n=t.useRef(null),s=t.useRef({width:0,height:0,top:0,left:0}),{nonce:o}=t.useContext(b);return t.useInsertionEffect(()=>{const{width:l,height:r,top:h,left:i}=s.current;if(f||!n.current||!l||!r)return;n.current.dataset.motionPopId=e;const c=document.createElement("style");return o&&(c.nonce=o),document.head.appendChild(c),c.sheet&&c.sheet.insertRule(`
          [data-motion-pop-id="${e}"] {
            position: absolute !important;
            width: ${l}px !important;
            height: ${r}px !important;
            top: ${h}px !important;
            left: ${i}px !important;
          }
        `),()=>{document.head.removeChild(c)}},[f]),m.jsx(K,{isPresent:f,childRef:n,sizeRef:s,children:t.cloneElement(u,{ref:n})})}const O=({children:u,initial:f,isPresent:e,onExitComplete:n,custom:s,presenceAffectsLayout:o,mode:l})=>{const r=L(U),h=t.useId(),i=t.useCallback(p=>{r.set(p,!0);for(const v of r.values())if(!v)return;n&&n()},[r,n]),c=t.useMemo(()=>({id:h,initial:f,isPresent:e,custom:s,onExitComplete:i,register:p=>(r.set(p,!1),()=>r.delete(p))}),o?[Math.random(),i]:[e,i]);return t.useMemo(()=>{r.forEach((p,v)=>r.set(v,!1))},[e]),t.useEffect(()=>{!e&&!r.size&&n&&n()},[e]),l==="popLayout"&&(u=m.jsx(N,{isPresent:e,children:u})),m.jsx(k.Provider,{value:c,children:u})};function U(){return new Map}const w=u=>u.key||"";function P(u){const f=[];return t.Children.forEach(u,e=>{t.isValidElement(e)&&f.push(e)}),f}const B=({children:u,custom:f,initial:e=!0,onExitComplete:n,presenceAffectsLayout:s=!0,mode:o="sync",propagate:l=!1})=>{const[r,h]=S(l),i=t.useMemo(()=>P(u),[u]),c=l&&!r?[]:i.map(w),p=t.useRef(!0),v=t.useRef(i),y=L(()=>new Map),[T,z]=t.useState(i),[C,M]=t.useState(i);$(()=>{p.current=!1,v.current=i;for(let d=0;d<C.length;d++){const a=w(C[d]);c.includes(a)?y.delete(a):y.get(a)!==!0&&y.set(a,!1)}},[C,c.length,c.join("-")]);const E=[];if(i!==T){let d=[...i];for(let a=0;a<C.length;a++){const x=C[a],R=w(x);c.includes(R)||(d.splice(a,0,x),E.push(x))}o==="wait"&&E.length&&(d=E),M(P(d)),z(i);return}const{forceRender:g}=t.useContext(A);return m.jsx(m.Fragment,{children:C.map(d=>{const a=w(d),x=l&&!r?!1:i===C||c.includes(a),R=()=>{if(y.has(a))y.set(a,!0);else return;let j=!0;y.forEach(I=>{I||(j=!1)}),j&&(g==null||g(),M(v.current),l&&(h==null||h()),n&&n())};return m.jsx(O,{isPresent:x,initial:!p.current||e?void 0:!1,custom:x?void 0:f,presenceAffectsLayout:s,mode:o,onExitComplete:x?void 0:R,children:d},a)})})};function H(){const[u,f]=t.useState([]),[e,n]=t.useState(!1);return t.useEffect(()=>{const s=window.matchMedia("(prefers-reduced-motion: reduce)");n(s.matches);const o=l=>n(l.matches);return s.addEventListener("change",o),()=>s.removeEventListener("change",o)},[]),t.useEffect(()=>{if(e)return;let s,o=0;const l=r=>{const h={x:r.clientX,y:r.clientY,id:o++};f(i=>{const c=[...i,h];return c.length>15&&c.shift(),c}),clearTimeout(s),s=setTimeout(()=>{f([])},100)};return window.addEventListener("mousemove",l),()=>{window.removeEventListener("mousemove",l),clearTimeout(s)}},[e]),e?null:m.jsx("div",{className:"pointer-events-none fixed inset-0 z-[9999] overflow-hidden",children:m.jsx(B,{children:u.map((s,o)=>m.jsx(D.div,{initial:{opacity:.8,scale:1},animate:{opacity:0,scale:.2},exit:{opacity:0},transition:{duration:.5,ease:"easeOut"},className:"absolute w-3 h-3 rounded-full",style:{left:s.x-6,top:s.y-6,background:o%3===0?"#ff00ff":o%3===1?"#00ffff":"#39ff14",boxShadow:`0 0 10px ${o%3===0?"#ff00ff":o%3===1?"#00ffff":"#39ff14"}`}},s.id))})})}export{B as A,H as C};
